export const SEED = [
  {
    "id": "seed_rina_runarina",
    "name": "琴音リナ🌙🌟ギャルゲ450本プレイ",
    "xId": "rina_runarina",
    "xLink": "https://x.com/rina_runarina",
    "followers": 20000,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_erina_ppcc",
    "name": "erina｜THE GAME SQUARE",
    "xId": "erina_ppcc",
    "xLink": "https://x.com/erina_ppcc",
    "followers": 10000,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_Satori_310ri",
    "name": "碁理🧩🐰",
    "xId": "Satori_310ri",
    "xLink": "https://x.com/Satori_310ri",
    "followers": 7498,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_yoppy_dayon",
    "name": "よびちゃんねる✨個人Vtuber",
    "xId": "yoppy_dayon",
    "xLink": "https://x.com/yoppy_dayon",
    "followers": 5289,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_Ui__Ren",
    "name": "卯依れん/ういれん 3DLiveありがとう🐰",
    "xId": "Ui__Ren",
    "xLink": "https://x.com/Ui__Ren",
    "followers": 5229,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_JELLY_game003",
    "name": "Mila🦋",
    "xId": "JELLY_game003",
    "xLink": "https://x.com/JELLY_game003",
    "followers": 34000,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_ui_0u0_",
    "name": "雪咲うい🧸🌸*",
    "xId": "ui_0u0_",
    "xLink": "https://x.com/ui_0u0_",
    "followers": 2700,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_konya0924",
    "name": "こな-kona-@comms open!",
    "xId": "konya0924",
    "xLink": "https://x.com/konya0924",
    "followers": 2596,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_sua_o1",
    "name": "Su!..A?",
    "xId": "sua_o1",
    "xLink": "https://x.com/sua_o1",
    "followers": 2305,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_dc5_6700zur8r9",
    "name": "れいる",
    "xId": "dc5_6700zur8r9",
    "xLink": "https://x.com/dc5_6700zur8r9",
    "followers": 2162,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_krr_spr",
    "name": "kurara",
    "xId": "krr_spr",
    "xLink": "https://x.com/krr_spr",
    "followers": 2025,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_bananamilk_ch",
    "name": "ばななみるく🍌🥛",
    "xId": "bananamilk_ch",
    "xLink": "https://x.com/bananamilk_ch",
    "followers": 1865,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_honoka_team2bro",
    "name": "ほのか🌸⋆꙳",
    "xId": "honoka_team2bro",
    "xLink": "https://x.com/honoka_team2bro",
    "followers": 1764,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_s_ena8",
    "name": "SENA（ˇ ˇ）!!!",
    "xId": "s_ena8",
    "xLink": "https://x.com/s_ena8",
    "followers": 1531,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_koduki_ragi",
    "name": "紺月らぎ🌙💎⟡.",
    "xId": "koduki_ragi",
    "xLink": "https://x.com/koduki_ragi",
    "followers": 1378,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_plidqy0p",
    "name": "ぴぃぃ",
    "xId": "plidqy0p",
    "xLink": "https://x.com/plidqy0p",
    "followers": 1364,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_onakasuita_na",
    "name": "n a c o ☁️",
    "xId": "onakasuita_na",
    "xLink": "https://x.com/onakasuita_na",
    "followers": 357,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_Lthe1101",
    "name": "眠兎える",
    "xId": "Lthe1101",
    "xLink": "https://x.com/Lthe1101",
    "followers": 1238,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_rctbby",
    "name": "rica",
    "xId": "rctbby",
    "xLink": "https://x.com/rctbby",
    "followers": 1044,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_sakanaosushi",
    "name": "sakana🐟",
    "xId": "sakanaosushi",
    "xLink": "https://x.com/sakanaosushi",
    "followers": 895,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_newprismplains",
    "name": "かの",
    "xId": "newprismplains",
    "xLink": "https://x.com/newprismplains",
    "followers": 853,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_YutoMuchiko",
    "name": "幽灯むち子🐼🕯",
    "xId": "YutoMuchiko",
    "xLink": "https://x.com/YutoMuchiko",
    "followers": 835,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_nicocyan0117",
    "name": "nicoちゃん",
    "xId": "nicocyan0117",
    "xLink": "https://x.com/nicocyan0117",
    "followers": 820,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_watamoti_game",
    "name": "わたもち",
    "xId": "watamoti_game",
    "xLink": "https://x.com/watamoti_game",
    "followers": 667,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_saban_gamemv",
    "name": "saban（さばん）",
    "xId": "saban_gamemv",
    "xLink": "https://x.com/saban_gamemv",
    "followers": 544,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_meuxy_UoxoU",
    "name": "楓にゃん9ℊ 2.5次元Vtuber",
    "xId": "meuxy_UoxoU",
    "xLink": "https://x.com/meuxy_UoxoU",
    "followers": 523,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_yuku__x",
    "name": "ゆくく",
    "xId": "yuku__x",
    "xLink": "https://x.com/yuku__x",
    "followers": 451,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_t0rotakugauu",
    "name": "とろたく。・`∂ℊ",
    "xId": "t0rotakugauu",
    "xLink": "https://x.com/t0rotakugauu",
    "followers": 417,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_minato_V1224",
    "name": "明雪みなと",
    "xId": "minato_V1224",
    "xLink": "https://x.com/minato_V1224",
    "followers": 294,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_lilyqiimelo",
    "name": "ゆりめろ🧸*",
    "xId": "lilyqiimelo",
    "xLink": "https://x.com/lilyqiimelo",
    "followers": 120,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_peersalvia_blue",
    "name": "ぺるびあぷるー",
    "xId": "peersalvia_blue",
    "xLink": "https://x.com/peersalvia_blue",
    "followers": 111,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_mimiko_mimi_mi",
    "name": "みみこ",
    "xId": "mimiko_mimi_mi",
    "xLink": "https://x.com/mimiko_mimi_mi",
    "followers": 110,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_Yu_wi_06",
    "name": "Yu.",
    "xId": "Yu_wi_06",
    "xLink": "https://x.com/Yu_wi_06",
    "followers": 71,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_Tora__gg",
    "name": "Tora🐯💗",
    "xId": "Tora__gg",
    "xLink": "https://x.com/Tora__gg",
    "followers": 25,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_cnvu_7",
    "name": "vivi",
    "xId": "cnvu_7",
    "xLink": "https://x.com/cnvu_7",
    "followers": 19,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_mejiro75",
    "name": "めじろ🕊️",
    "xId": "mejiro75",
    "xLink": "https://x.com/mejiro75",
    "followers": 17,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_hqcuu_47",
    "name": "^uu'z",
    "xId": "hqcuu_47",
    "xLink": "https://x.com/hqcuu_47",
    "followers": 3,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_Oo_syk_oO",
    "name": "𝕊",
    "xId": "Oo_syk_oO",
    "xLink": "https://x.com/Oo_syk_oO",
    "followers": 1336,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  },
  {
    "id": "seed_marudaiTime",
    "name": "まるだい きみ ♡ Twitch",
    "xId": "marudaiTime",
    "xLink": "https://x.com/marudaiTime",
    "followers": 631,
    "following": null,
    "color": "",
    "status": "検討中",
    "otherSns": [],
    "prPosts": [],
    "photos": [],
    "note": ""
  }
];
